export const womemProducts = [
  {
    id: 1,
    image: "product1Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 2,
    image: "product2Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 3,
    image: "product3Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 4,
    image: "product4Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 5,
    image: "product1Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
    discountPrice: 99,
  },
  {
    id: 6,
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    image: "product2Women",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 7,
    image: "product3Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 8,
    image: "product4Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 9,
    image: "product1Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 10,
    image: "product2Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 11,
    image: "product3Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 12,
    image: "product4Women",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
]

export const mensProducts = [
  {
    id: 13,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "product4Women", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 14,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
    discountPrice: 99,
  },
  {
    id: 15,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 16,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 17,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
    discountPrice: 99,
  },
  {
    id: 18,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 19,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 20,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 21,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
    discountPrice: 99,
  },
  {
    id: 22,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 23,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
  {
    id: 24,
    image: "product1Men",
    name: "RECYCLED POLYESTER PERFORMANCE PARKA",
    price: 135,
    currency: "€",
    description: `Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.`,
    properties: [
      "Relaxed fit",
      "Dropped Shoulder",
      "Elastic body",
      "Ribbed cuff",
    ],
    material:
      "32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable",
    sizeDescription: "Back length of size XS/S is 70cm",
    variants: [
      { name: "", image: "/images/womens/product1Men.png", type: "" },
      { name: "", image: "product4WomenVariant1", type: "" },
      { name: "", image: "product4WomenVariant2", type: "" },
      { name: "", image: "product4WomenVariant3", type: "" },
      { name: "", image: "product4WomenVariant4", type: "" },
    ],
    code: "0930647001",
    customerMessage: `Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products.`,
  },
]
